### PR TITLE
Update changes at google to r456

### PR DESCRIPTION
**Pull request by tkruse**
Hi,

it seems cpplint is not quite dead at google, they just do the development in their SVN repo, which is not public anymore (which is a real pity), and they kind of ignore pull requests at github for cpplint.

This PR merges https://github.com/google/styleguide/pull/130
into master, and to make things a bit more obvious, I merged with the latest gh_pages branch.

I think this should better be merged before #11, #12, #13, #14, #15, #16 
because the google development should take precedence. Then we'd have to rebase.

### CODE REVIEW

**Comment by tkruse** [comment]
note you can ignore the contents of all the commits except for mine and 01e4723, because they deal with upstream changes to files that are deleted on this fork.

**Comment by tkruse** [comment]
Also note that google has removed certain rules, so it has relaxed some style checks. Maybe that should be reflected in the released cpplint version number.

**Comment by thomasjo** [comment]
Is there anything I can help out with to get this shipping? I'm vendoring this version of `cpplint.py` right now, but it'd be awesome to be able to fall back to PyPI again.

**Comment by tkruse** [comment]
Hm, I pinged @theandrewdavis by mail...

**Comment by theandrewdavis** [comment]
I believe this was superseded by #22 which is now merged

**Pull request closed without merging**
