### PR TITLE
Regression tests

### PR DESCRIPTION
**Pull request by tkruse**
This is a new test for regressions, running cpplint against some samples I pulled from here and there, and making sure output stays the same. In some cases, python2 and python3 will use different sorting for sets and dicts, in those cases output should be sorted to make wiritng tests pass (and also for usability).

### CODE REVIEW

**Comment by theandrewdavis** [comment]
This PR seems to have removed the pylint checking you added earlier. I'm guessing that wasn't intended, so I left it in

**Comment by theandrewdavis** [comment]
Oh, I see now that you are replacing pylint with pyflakes and that's why the pylint was removed. I'm guessing you intended pyflakes to run in travis, so I changed the `python cpplint.py` and similar lines in travis.yml to `pyflakes cpplint.py`

**Comment by tkruse** [comment]
Honestly I cannot remember, but it would be more like me to try and have both pylint and pyflakes...

**Comment by tkruse** [comment]
Seemssome things got lost during rebases, here is the original commit:
https://github.com/tkruse/cpplint/pull/32/commits/ddb5392e02

**Comment by tkruse** [comment]
Yes, I suggest to have all 3 on travis:
* pylint
* pyflakes
* run python cpplint with unittests, clitests, and --help

**Pull request merged**
